Name: extensions
---
Member:
  extensions:
    - 'SalesforceAuthMemberExtension'

---
Name: routes
After:
  - '#coreroutes'
  - '#modelascontrollerroutes'
---
Director:
  rules:
    'salesforce-auth': 'SalesforceAuthController'
